name: "Load Terraform Outputs"
description: "Fetches Terraform state from S3, extracts outputs, and uploads as artifact"

inputs:
  environment:
    description: "Environment name (dev, stage, prod)"
    required: true
  aws-access-key-id:
    description: "AWS Access Key ID"
    required: true
  aws-secret-access-key:
    description: "AWS Secret Access Key"
    required: true
  aws-region:
    description: "AWS Region"
    default: "us-east-1"
  aws-account-id:
    description: "AWS Account ID"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install jq
      run: sudo apt-get update && sudo apt-get install -y jq
      shell: bash

    - name: Debug AWS secret key
      run: |
        echo "Key length: ${#AWS_SECRET_ACCESS_KEY}"
        echo -n "$AWS_SECRET_ACCESS_KEY" | od -c
      shell: bash
      env:
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Download Terraform state
      run: |
        echo "Downloading state for environment: ${{ inputs.environment }}"
        aws s3 cp "s3://${{ inputs.aws-account-id }}-app-dev/env:/${{ inputs.environment }}/networking/terraform.tfstate" terraform.tfstate
      shell: bash

    - name: Extract outputs -> file
      run: |
        jq -r '{frontend_url: .outputs.frontend_repository_url.value, backend_url: .outputs.backend_repository_url.value}' terraform.tfstate > tf-outputs.json
        echo "Extracted terraform outputs:"
        cat tf-outputs.json
      shell: bash

    - name: Upload TF outputs artifact
      uses: actions/upload-artifact@v4
      with:
        name: tf-outputs
        path: tf-outputs.json
